### ISSUE TITLE
2019.1.7

### ISSUE THREAD

**Issue by ZhechenLi** [ZhechenLi/I-O-P#1]
- ### 查找有哪些算法
> 对无序表
- 顺序查找
> 对有序表
- 二分查找(对半分,每次查找少一半工作量,相当于二叉树,查找次数为树深度:log2N+1)
- 插值查找(要查的 key 和最大最小值比较,有个换算公式,找到区分点;比如查 apple 就在字典的前区找)
- 菲波列切查找 (根据黄金分割点找)
> 索引
- 线性\树形\多级索引
> 线性索引
- 稠密索引(每个 key,都有一个索引)
- 分块索引(每个 key,对应一块区间,块内无序,块间有序)
- 倒排索引(也叫反向索引,次关键字->关键字->值)
> 树查找
- 二叉排序树(左子树<根<右子树)
- 平衡二叉树(左子树和右子树高度差,绝对值不超过1,为严格平衡)
- 红黑树(非严格平衡)
- B-tree(分块索引+块内有序,一般孩子节点为块内元素个数,效率最优)
- B+tree(叶子节点有所有数据,且有指针指向下一个节点)
> 哈希查找
- 哈希函数选取(djbhash,一般为除留余数法)
- 哈希冲突解法(线性探测再散列,再哈希,拉链法)

- ### 正则的正向
```js
const text = `<div>innerHTML</div><span>innerHTML</span>`;

// 零宽正向先行断言
// 匹配后面是 </div> 的 innerHTML
/innerHTML(?=\<\/div\>)/.exec(text);

// 零宽负向先行断言
// 匹配后面不是 </div> 的 innerHTML
/innerHTML(?!\<\/div\>)/.exec(text);

// 零宽正向后行断言
// 匹配前面是 <div> 的 innerHTML
/(?<=\<\/div\>)innerHTML/.exec(text);

// 零宽负向后行断言
// 匹配前面是 <div> 的 innerHTML
/(?<!\<\/div\>)innerHTML/.exec(text);
```
- ### 富文本的坑
没做过
- ### 千分位
```js
(100000).toLocaleString()
// 更通用的版本
new Intl.NumberFormat().format('100000000')
```
- ### new 过程
```js
function XiaoMing(id) {
  this.id = id;
}

XiaoMing.prototype.aloha = function() {
  console.log(`Aloha, I'm XiaoMing:${this.id}.`);
};

// const xiaoMing_1 = new XiaoMing(30624700);
// xiaoMing_1.aloha();

const xiaoMing_2 = {};
XiaoMing.call(xiaoMing_2, 30624770);
xiaoMing_2.__proto__ = XiaoMing.prototype;
xiaoMing_2.aloha();
```

**Comment by ameriania** [comment]
good job 每日一练

**Comment by ameriania** [comment]
做完
